language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get install lua5.2
  - printf "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1

after_success:
  - chmod +x .travis/push.sh
  - ./.travis/push.sh
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload